// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Runtime config (para deploy self-hosted)
declare global {
  interface Window {
    __SUPABASE_CONFIG__?: {
      url: string;
      anonKey: string;
    };
  }
}

// Usar runtime config se disponível, senão usar variáveis de ambiente
const getRuntimeConfig = () => {
  // Runtime config (config.js no VPS) SEMPRE tem prioridade
  const runtimeConfig = window.__SUPABASE_CONFIG__;
  if (runtimeConfig?.url && runtimeConfig?.anonKey) {
    return { url: runtimeConfig.url, key: runtimeConfig.anonKey };
  }
  
  // Fallback: variáveis de ambiente compiladas (Lovable Cloud)
  return {
    url: import.meta.env.VITE_SUPABASE_URL,
    key: import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY
  };
};

const config = getRuntimeConfig();
const SUPABASE_URL = config.url;
const SUPABASE_PUBLISHABLE_KEY = config.key;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});